version: '2'

services:
  dicom_anon:
    restart: always
    build: ./dicom_anon
    volumes:
      - ./input:/input
      - ./output:/output
      - ./quarantine:/quarantine
  fullanon:
    restart: always
    build: ./fullanon
    volumes:
      - ./input:/input
      - ./output:/output